http:
  port: "8081"
 
api:
  id: "20324039"
 
request:
  host: "s-test-molmedomarin-k9u1m0.5sc6y6-3.usa-e2.cloudhub.io"
  port: "8081"
  basepath: "/"
  protocol: "HTTP"

s_layer:
  client_id: "![PKTv8m5YsimrbHwBS/3wJua6Xqt5qEw25Pmf8b3Vm052rttFnuUGcA==]"
  client_secret: "![L6bS2K2+RpijCDcdFCHXfX1W5p/0XHUwsJx5QVzCqBnwsQBHFIBr7Q==]"
